# Generated by Django 5.0.2 on 2024-06-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
