# Generated by Django 5.0.2 on 2024-06-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_customuser_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_date',
            field=models.DateField(null=True),
        ),
    ]
