# Generated by Django 5.0.2 on 2024-06-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_customuser_submission_date_customuser_submitted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='submission_date',
            new_name='submission_date_assignment',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='submitted',
            new_name='submitted_assignment',
        ),
        migrations.AddField(
            model_name='customuser',
            name='submission_date_internal',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='submission_date_practical',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='submitted_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='submitted_practical',
            field=models.BooleanField(default=False),
        ),
    ]
