# Generated by Django 5.0.2 on 2024-06-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_rename_submission_date_customuser_submission_date_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='submission_date_assignment',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='submission_date_internal',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='submission_date_practical',
        ),
    ]
