# Generated by Django 5.0.2 on 2024-06-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_remove_customuser_submission_date_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='submission_date_assignment',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='submission_date_internal',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='submission_date_practical',
            field=models.DateField(null=True),
        ),
    ]
