# Generated by Django 5.0.2 on 2024-07-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_customuser_center_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='center_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='submission_date_center',
            field=models.DateField(null=True),
        ),
    ]
