# Generated by Django 5.0.2 on 2024-06-10 07:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_tp_dob_alter_tp_date_of_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tp',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
