# Generated by Django 5.0.2 on 2024-06-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_tp_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='tp',
            name='IS1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tp',
            name='IS2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
