# Generated by Django 5.0.2 on 2024-06-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_tp_is1_tp_is2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tp',
            name='center_code',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
