# Generated by Django 5.0.2 on 2024-07-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_tp_center_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tp',
            old_name='center_code',
            new_name='Center_code',
        ),
    ]
